### PR TITLE
Provide a configuration option to disable reverse dns lookups

### PR DESCRIPTION
**Pull request by furkanmustafa**

### CODE REVIEW

**Comment by andris9** [comment]
What is the use case here? If reverse resolving fails then the error is ignored so the current behavior should not be an issue?

**Comment by furkanmustafa** [comment]
When reverse resolving fails, it is working OK but adding too much delay to delivery depending on how it fails. For the internal network usage, that was a problem.

**Comment by andris9** [comment]
fair enough, thanks

**Comment by andris9** [comment]
Changed it a bit though. I don't really like default options that are `true` so I renamed the option to `disableReverseLookup` and the default for it is `false`. Published as v1.13.0

**Comment by furkanmustafa** [comment]
Thanks!

**Pull request merged**
